# Generated by Django 4.2.16 on 2024-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercluster',
            name='clustering_method',
            field=models.CharField(default='K-Means', max_length=50),
        ),
    ]
